# Numpy <hr style="border:2.5px dotted rgba(61, 19, 77, 1)"></hr>


<b>Mel Justin M. Villa</b>
<br>Computer Engineering Student at <a href="https://www.tup.edu.ph" target="_blank">TUPV</a>
<br>Contact me at: <a href="mailto:melv.online05@gmail.com">melv.online05@gmail.com</a><br>


In [93]:
#import and packages
import numpy as np

In [94]:
my_array = [1,2,3]

In [95]:
type(my_array)

list

In [96]:
my_array = np.array([1,2,3])

In [97]:
np.shape(my_array)

(3,)

<b><h1>2D array</b></h1>

In [98]:
my_array = np.array([
    [1,2,3],
    [4,5,6],
])


In [99]:
np.shape(my_array)

(2, 3)

In [100]:
trans_array=my_array.T

In [101]:
np.shape(trans_array)

(3, 2)

In [102]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [103]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

<b><h1>Measure of Central Tendency</b></h1>

In [104]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [105]:
#Mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [106]:
row1 = resistance[0]
row2 = resistance[1]

In [107]:
row1

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [108]:
row2

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan])

In [109]:
median_row1 = np.nanmedian(resistance[0])
median_row2 = np.nanmedian(resistance[1])
median_row1

np.float64(9.8)

In [110]:
median_row2

np.float64(9.55)

In [111]:
values, counts = np.unique(row1, return_counts=True)

mxcount = np.max(counts)
modes_row1 = values[counts == max_count]
modes_row1

array([ 9.8, 10.4])

In [112]:
row2 = row2[~np.isnan(row2)]   # remove NaN

values2, counts2 = np.unique(row2, return_counts=True)
mode_row2 = values2[np.argmax(counts2)]
mode_row2

np.float64(9.1)

<b><h1>Variation</b></h1>

In [113]:
std_row1 = np.std(row1)
std_row1

np.float64(2.101947149236112)

In [114]:
std_row2 = np.std(row2)
std_row2

np.float64(3.1582431825304393)

In [115]:
var_row1 = np.var(row1)
var_row1

np.float64(4.418181818181818)

In [116]:
var_row2 = np.var(row2)
var_row2

np.float64(9.974499999999999)